// Code generated by ent, DO NOT EDIT.

package agenttask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agenttask type in the database.
	Label = "agent_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldAgentType holds the string denoting the agent_type field in the database.
	FieldAgentType = "agent_type"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldSpanID holds the string denoting the span_id field in the database.
	FieldSpanID = "span_id"
	// FieldParentSpanID holds the string denoting the parent_span_id field in the database.
	FieldParentSpanID = "parent_span_id"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// FieldOutput holds the string denoting the output field in the database.
	FieldOutput = "output"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldLlmCallCount holds the string denoting the llm_call_count field in the database.
	FieldLlmCallCount = "llm_call_count"
	// FieldToolCallCount holds the string denoting the tool_call_count field in the database.
	FieldToolCallCount = "tool_call_count"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldTokensPrompt holds the string denoting the tokens_prompt field in the database.
	FieldTokensPrompt = "tokens_prompt"
	// FieldTokensCompletion holds the string denoting the tokens_completion field in the database.
	FieldTokensCompletion = "tokens_completion"
	// FieldTokensTotal holds the string denoting the tokens_total field in the database.
	FieldTokensTotal = "tokens_total"
	// FieldCostUsd holds the string denoting the cost_usd field in the database.
	FieldCostUsd = "cost_usd"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// EdgeToolInvocations holds the string denoting the tool_invocations edge name in mutations.
	EdgeToolInvocations = "tool_invocations"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the agenttask in the database.
	Table = "agent_tasks"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "agent_tasks"
	// WorkflowInverseTable is the table name for the Workflow entity.
	// It exists in this package in order to avoid circular dependency with the "workflow" package.
	WorkflowInverseTable = "workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "workflow_id"
	// ToolInvocationsTable is the table that holds the tool_invocations relation/edge.
	ToolInvocationsTable = "tool_invocations"
	// ToolInvocationsInverseTable is the table name for the ToolInvocation entity.
	// It exists in this package in order to avoid circular dependency with the "toolinvocation" package.
	ToolInvocationsInverseTable = "tool_invocations"
	// ToolInvocationsColumn is the table column denoting the tool_invocations relation/edge.
	ToolInvocationsColumn = "task_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "agent_events"
	// EventsInverseTable is the table name for the AgentEvent entity.
	// It exists in this package in order to avoid circular dependency with the "agentevent" package.
	EventsInverseTable = "agent_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "task_id"
)

// Columns holds all SQL columns for agenttask fields.
var Columns = []string{
	FieldID,
	FieldWorkflowID,
	FieldAgentID,
	FieldAgentType,
	FieldTaskType,
	FieldName,
	FieldStatus,
	FieldTraceID,
	FieldSpanID,
	FieldParentSpanID,
	FieldInput,
	FieldOutput,
	FieldMetadata,
	FieldLlmCallCount,
	FieldToolCallCount,
	FieldRetryCount,
	FieldTokensPrompt,
	FieldTokensCompletion,
	FieldTokensTotal,
	FieldCostUsd,
	FieldDurationMs,
	FieldErrorType,
	FieldErrorMessage,
	FieldStartedAt,
	FieldEndedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	AgentIDValidator func(string) error
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultLlmCallCount holds the default value on creation for the "llm_call_count" field.
	DefaultLlmCallCount int
	// DefaultToolCallCount holds the default value on creation for the "tool_call_count" field.
	DefaultToolCallCount int
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultTokensPrompt holds the default value on creation for the "tokens_prompt" field.
	DefaultTokensPrompt int
	// DefaultTokensCompletion holds the default value on creation for the "tokens_completion" field.
	DefaultTokensCompletion int
	// DefaultTokensTotal holds the default value on creation for the "tokens_total" field.
	DefaultTokensTotal int
	// DefaultCostUsd holds the default value on creation for the "cost_usd" field.
	DefaultCostUsd float64
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AgentTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByAgentType orders the results by the agent_type field.
func ByAgentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentType, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// BySpanID orders the results by the span_id field.
func BySpanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpanID, opts...).ToFunc()
}

// ByParentSpanID orders the results by the parent_span_id field.
func ByParentSpanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentSpanID, opts...).ToFunc()
}

// ByLlmCallCount orders the results by the llm_call_count field.
func ByLlmCallCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmCallCount, opts...).ToFunc()
}

// ByToolCallCount orders the results by the tool_call_count field.
func ByToolCallCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolCallCount, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByTokensPrompt orders the results by the tokens_prompt field.
func ByTokensPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensPrompt, opts...).ToFunc()
}

// ByTokensCompletion orders the results by the tokens_completion field.
func ByTokensCompletion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensCompletion, opts...).ToFunc()
}

// ByTokensTotal orders the results by the tokens_total field.
func ByTokensTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensTotal, opts...).ToFunc()
}

// ByCostUsd orders the results by the cost_usd field.
func ByCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsd, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}

// ByToolInvocationsCount orders the results by tool_invocations count.
func ByToolInvocationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newToolInvocationsStep(), opts...)
	}
}

// ByToolInvocations orders the results by tool_invocations terms.
func ByToolInvocations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToolInvocationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
func newToolInvocationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToolInvocationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ToolInvocationsTable, ToolInvocationsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
