// Code generated by ent, DO NOT EDIT.

package toolinvocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the toolinvocation type in the database.
	Label = "tool_invocation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldToolName holds the string denoting the tool_name field in the database.
	FieldToolName = "tool_name"
	// FieldToolType holds the string denoting the tool_type field in the database.
	FieldToolType = "tool_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldSpanID holds the string denoting the span_id field in the database.
	FieldSpanID = "span_id"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// FieldOutput holds the string denoting the output field in the database.
	FieldOutput = "output"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldHTTPMethod holds the string denoting the http_method field in the database.
	FieldHTTPMethod = "http_method"
	// FieldHTTPURL holds the string denoting the http_url field in the database.
	FieldHTTPURL = "http_url"
	// FieldHTTPStatusCode holds the string denoting the http_status_code field in the database.
	FieldHTTPStatusCode = "http_status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldRequestSizeBytes holds the string denoting the request_size_bytes field in the database.
	FieldRequestSizeBytes = "request_size_bytes"
	// FieldResponseSizeBytes holds the string denoting the response_size_bytes field in the database.
	FieldResponseSizeBytes = "response_size_bytes"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// Table holds the table name of the toolinvocation in the database.
	Table = "tool_invocations"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "tool_invocations"
	// TaskInverseTable is the table name for the AgentTask entity.
	// It exists in this package in order to avoid circular dependency with the "agenttask" package.
	TaskInverseTable = "agent_tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
)

// Columns holds all SQL columns for toolinvocation fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldAgentID,
	FieldToolName,
	FieldToolType,
	FieldStatus,
	FieldTraceID,
	FieldSpanID,
	FieldInput,
	FieldOutput,
	FieldMetadata,
	FieldHTTPMethod,
	FieldHTTPURL,
	FieldHTTPStatusCode,
	FieldDurationMs,
	FieldRequestSizeBytes,
	FieldResponseSizeBytes,
	FieldRetryCount,
	FieldErrorType,
	FieldErrorMessage,
	FieldStartedAt,
	FieldEndedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	AgentIDValidator func(string) error
	// ToolNameValidator is a validator for the "tool_name" field. It is called by the builders before save.
	ToolNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultRequestSizeBytes holds the default value on creation for the "request_size_bytes" field.
	DefaultRequestSizeBytes int
	// DefaultResponseSizeBytes holds the default value on creation for the "response_size_bytes" field.
	DefaultResponseSizeBytes int
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ToolInvocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByToolName orders the results by the tool_name field.
func ByToolName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolName, opts...).ToFunc()
}

// ByToolType orders the results by the tool_type field.
func ByToolType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// BySpanID orders the results by the span_id field.
func BySpanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpanID, opts...).ToFunc()
}

// ByHTTPMethod orders the results by the http_method field.
func ByHTTPMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPMethod, opts...).ToFunc()
}

// ByHTTPURL orders the results by the http_url field.
func ByHTTPURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPURL, opts...).ToFunc()
}

// ByHTTPStatusCode orders the results by the http_status_code field.
func ByHTTPStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByRequestSizeBytes orders the results by the request_size_bytes field.
func ByRequestSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestSizeBytes, opts...).ToFunc()
}

// ByResponseSizeBytes orders the results by the response_size_bytes field.
func ByResponseSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseSizeBytes, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
	)
}
