// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentEvent is the predicate function for agentevent builders.
type AgentEvent func(*sql.Selector)

// AgentHandoff is the predicate function for agenthandoff builders.
type AgentHandoff func(*sql.Selector)

// AgentTask is the predicate function for agenttask builders.
type AgentTask func(*sql.Selector)

// ToolInvocation is the predicate function for toolinvocation builders.
type ToolInvocation func(*sql.Selector)

// Workflow is the predicate function for workflow builders.
type Workflow func(*sql.Selector)
