// Code generated by ent, DO NOT EDIT.

package agenthandoff

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agenthandoff type in the database.
	Label = "agent_handoff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldFromAgentID holds the string denoting the from_agent_id field in the database.
	FieldFromAgentID = "from_agent_id"
	// FieldFromAgentType holds the string denoting the from_agent_type field in the database.
	FieldFromAgentType = "from_agent_type"
	// FieldToAgentID holds the string denoting the to_agent_id field in the database.
	FieldToAgentID = "to_agent_id"
	// FieldToAgentType holds the string denoting the to_agent_type field in the database.
	FieldToAgentType = "to_agent_type"
	// FieldHandoffType holds the string denoting the handoff_type field in the database.
	FieldHandoffType = "handoff_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldFromTaskID holds the string denoting the from_task_id field in the database.
	FieldFromTaskID = "from_task_id"
	// FieldToTaskID holds the string denoting the to_task_id field in the database.
	FieldToTaskID = "to_task_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldPayloadSizeBytes holds the string denoting the payload_size_bytes field in the database.
	FieldPayloadSizeBytes = "payload_size_bytes"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldInitiatedAt holds the string denoting the initiated_at field in the database.
	FieldInitiatedAt = "initiated_at"
	// FieldAcceptedAt holds the string denoting the accepted_at field in the database.
	FieldAcceptedAt = "accepted_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// Table holds the table name of the agenthandoff in the database.
	Table = "agent_handoffs"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "agent_handoffs"
	// WorkflowInverseTable is the table name for the Workflow entity.
	// It exists in this package in order to avoid circular dependency with the "workflow" package.
	WorkflowInverseTable = "workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "workflow_id"
)

// Columns holds all SQL columns for agenthandoff fields.
var Columns = []string{
	FieldID,
	FieldWorkflowID,
	FieldFromAgentID,
	FieldFromAgentType,
	FieldToAgentID,
	FieldToAgentType,
	FieldHandoffType,
	FieldStatus,
	FieldTraceID,
	FieldFromTaskID,
	FieldToTaskID,
	FieldPayload,
	FieldMetadata,
	FieldPayloadSizeBytes,
	FieldLatencyMs,
	FieldErrorMessage,
	FieldInitiatedAt,
	FieldAcceptedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FromAgentIDValidator is a validator for the "from_agent_id" field. It is called by the builders before save.
	FromAgentIDValidator func(string) error
	// ToAgentIDValidator is a validator for the "to_agent_id" field. It is called by the builders before save.
	ToAgentIDValidator func(string) error
	// DefaultHandoffType holds the default value on creation for the "handoff_type" field.
	DefaultHandoffType string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPayloadSizeBytes holds the default value on creation for the "payload_size_bytes" field.
	DefaultPayloadSizeBytes int
	// DefaultInitiatedAt holds the default value on creation for the "initiated_at" field.
	DefaultInitiatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AgentHandoff queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByFromAgentID orders the results by the from_agent_id field.
func ByFromAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAgentID, opts...).ToFunc()
}

// ByFromAgentType orders the results by the from_agent_type field.
func ByFromAgentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAgentType, opts...).ToFunc()
}

// ByToAgentID orders the results by the to_agent_id field.
func ByToAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToAgentID, opts...).ToFunc()
}

// ByToAgentType orders the results by the to_agent_type field.
func ByToAgentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToAgentType, opts...).ToFunc()
}

// ByHandoffType orders the results by the handoff_type field.
func ByHandoffType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandoffType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByFromTaskID orders the results by the from_task_id field.
func ByFromTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromTaskID, opts...).ToFunc()
}

// ByToTaskID orders the results by the to_task_id field.
func ByToTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToTaskID, opts...).ToFunc()
}

// ByPayloadSizeBytes orders the results by the payload_size_bytes field.
func ByPayloadSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadSizeBytes, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByInitiatedAt orders the results by the initiated_at field.
func ByInitiatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatedAt, opts...).ToFunc()
}

// ByAcceptedAt orders the results by the accepted_at field.
func ByAcceptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
