// Code generated by ent, DO NOT EDIT.

package workflow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workflow type in the database.
	Label = "workflow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldParentWorkflowID holds the string denoting the parent_workflow_id field in the database.
	FieldParentWorkflowID = "parent_workflow_id"
	// FieldInitiator holds the string denoting the initiator field in the database.
	FieldInitiator = "initiator"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// FieldOutput holds the string denoting the output field in the database.
	FieldOutput = "output"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTaskCount holds the string denoting the task_count field in the database.
	FieldTaskCount = "task_count"
	// FieldCompletedTaskCount holds the string denoting the completed_task_count field in the database.
	FieldCompletedTaskCount = "completed_task_count"
	// FieldFailedTaskCount holds the string denoting the failed_task_count field in the database.
	FieldFailedTaskCount = "failed_task_count"
	// FieldTotalCostUsd holds the string denoting the total_cost_usd field in the database.
	FieldTotalCostUsd = "total_cost_usd"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// EdgeHandoffs holds the string denoting the handoffs edge name in mutations.
	EdgeHandoffs = "handoffs"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the workflow in the database.
	Table = "workflows"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "agent_tasks"
	// TasksInverseTable is the table name for the AgentTask entity.
	// It exists in this package in order to avoid circular dependency with the "agenttask" package.
	TasksInverseTable = "agent_tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "workflow_id"
	// HandoffsTable is the table that holds the handoffs relation/edge.
	HandoffsTable = "agent_handoffs"
	// HandoffsInverseTable is the table name for the AgentHandoff entity.
	// It exists in this package in order to avoid circular dependency with the "agenthandoff" package.
	HandoffsInverseTable = "agent_handoffs"
	// HandoffsColumn is the table column denoting the handoffs relation/edge.
	HandoffsColumn = "workflow_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "agent_events"
	// EventsInverseTable is the table name for the AgentEvent entity.
	// It exists in this package in order to avoid circular dependency with the "agentevent" package.
	EventsInverseTable = "agent_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "workflow_id"
)

// Columns holds all SQL columns for workflow fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatus,
	FieldTraceID,
	FieldParentWorkflowID,
	FieldInitiator,
	FieldInput,
	FieldOutput,
	FieldMetadata,
	FieldTaskCount,
	FieldCompletedTaskCount,
	FieldFailedTaskCount,
	FieldTotalCostUsd,
	FieldTotalTokens,
	FieldDurationMs,
	FieldErrorMessage,
	FieldStartedAt,
	FieldEndedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultTaskCount holds the default value on creation for the "task_count" field.
	DefaultTaskCount int
	// DefaultCompletedTaskCount holds the default value on creation for the "completed_task_count" field.
	DefaultCompletedTaskCount int
	// DefaultFailedTaskCount holds the default value on creation for the "failed_task_count" field.
	DefaultFailedTaskCount int
	// DefaultTotalCostUsd holds the default value on creation for the "total_cost_usd" field.
	DefaultTotalCostUsd float64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Workflow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByParentWorkflowID orders the results by the parent_workflow_id field.
func ByParentWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentWorkflowID, opts...).ToFunc()
}

// ByInitiator orders the results by the initiator field.
func ByInitiator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiator, opts...).ToFunc()
}

// ByTaskCount orders the results by the task_count field.
func ByTaskCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskCount, opts...).ToFunc()
}

// ByCompletedTaskCount orders the results by the completed_task_count field.
func ByCompletedTaskCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedTaskCount, opts...).ToFunc()
}

// ByFailedTaskCount orders the results by the failed_task_count field.
func ByFailedTaskCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedTaskCount, opts...).ToFunc()
}

// ByTotalCostUsd orders the results by the total_cost_usd field.
func ByTotalCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCostUsd, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHandoffsCount orders the results by handoffs count.
func ByHandoffsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHandoffsStep(), opts...)
	}
}

// ByHandoffs orders the results by handoffs terms.
func ByHandoffs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHandoffsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
func newHandoffsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HandoffsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HandoffsTable, HandoffsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
